name: PR validation (dev)

on:
  pull_request:
    branches: [dev]

jobs:
  build-test:
    runs-on: self-hosted

    steps:
      - name: Checkout merged commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Export vars from /opt/dev/env
        run: |
          ENV_FILE="/opt/dev/env"

          if [[ ! -f "$ENV_FILE" ]]; then
            echo "::error::File $ENV_FILE not found"
            exit 1
          fi

          echo "Using $ENV_FILE"
          echo "::group::Writing variables to GITHUB_ENV"
          while IFS='=' read -r key val || [[ -n "$key" ]]; do
            [[ "$key" =~ ^\s*# || -z "$key" ]] && continue
            echo "$key=$val" >> "$GITHUB_ENV"
          done < "$ENV_FILE"
          echo "::endgroup::"

          cp "$ENV_FILE" "$GITHUB_WORKSPACE/.env"
        shell: bash

      - name: Unit tests (Surefire)
        run: |
          mvn -B --no-transfer-progress \
              test-compile             \
              surefire:test
